[workspace]
members = [
  "crates/parser",
  "crates/tokenizer",
]

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
debug = true

[profile.bench]
codegen-units = 1
lto = true
panic = "abort"
debug = true
